# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20171130_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choices',
            field=models.CharField(choices=[('ascending', 'A-Z'), ('Hr', 'Highest Rating')], default='ascending', max_length=2),
        ),
    ]
