# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_product_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choices',
            field=models.CharField(choices=[('ascending', 'A-Z'), ('Hr', 'Highest Rating')], default='ascending', max_length=9),
        ),
    ]
